{
    'name': 'Mentorize',
    'version': '1.1.0',
    'summary': 'Platform Mentorship Alumni-Mahasiswa UNISA Yogyakarta',
    'description': 'Sistem mentoring berbasis web untuk menghubungkan mahasiswa dengan alumni sebagai mentor.',
    'author': 'Tim 3 - Teknologi Informasi UNISA',
    'category': 'Education',
    'depends': ['base', 'website', 'mail'],
    'data': [
        'security/mentorize_groups.xml',
        'security/ir.model.access.csv',
        'data/master_data.xml',
        'views/backend/admin_views.xml',
        'views/templates/layout.xml',
        'views/templates/landing.xml',
        'views/templates/login.xml',
        'views/templates/forgot_password.xml',
        'views/templates/register.xml',
        'views/templates/dashboard_mahasiswa.xml',
        'views/templates/dashboard_alumni.xml',
        'views/templates/dashboard_admin.xml',
        'views/templates/profil_mahasiswa.xml',
        'views/templates/mentors.xml',
        'views/templates/coming_soon.xml',
        'views/templates/sesi_mentoring_alumni.xml',
        'views/templates/sesi_mentoring_mahasiswa.xml',
        
    ],
    'assets': {
        'web.assets_frontend': [
            'mentorize/static/src/css/mentorize.css',
            'mentorize/static/src/xml/mentorize_components.xml',
            'mentorize/static/src/js/mentorize_owl.js',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
