{
    'name': 'Mentorize',
    'version': '2.0.0',
    'summary': 'Platform Mentorship Alumni-Mahasiswa UNISA Yogyakarta',
    'description': 'Custom website module untuk mentorship mahasiswa dan alumni dengan dashboard, profile, request mentoring, kalender, chat, notifikasi, dan riwayat.',
    'author': 'Tim 3 - Teknologi Informasi UNISA',
    'category': 'Education',
    'depends': ['base', 'web', 'website', 'mail', 'auth_signup'],
    'data': [
        'security/mentorize_groups.xml',
        'security/ir.model.access.csv',
        'data/mentorize_master_data.xml',
        'views/backend/admin_views.xml',
        'views/templates/layout.xml',
        'views/templates/public_pages.xml',
        'views/templates/dashboard_mahasiswa.xml',
        'views/templates/dashboard_alumni.xml',
        'views/templates/profile_pages.xml',
        'views/templates/mentor_pages.xml',
        'views/templates/chat_pages.xml',
        'views/templates/history_pages.xml',
        'views/templates/settings_pages.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'mentorize/static/src/css/mentorize.css',
            'mentorize/static/src/js/mentorize.js',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
