name: Deploy Mentorize to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "=== Mulai Deploy Mentorize ==="
            cd /opt/odoo/mentorize
            git pull origin Fix
            systemctl stop odoo17
            sudo -u odoo /opt/odoo/venv/bin/python /opt/odoo/odoo17/odoo-bin \
              -c /etc/odoo17.conf \
              -d Mentorize \
              -u mentorize \
              --stop-after-init
            systemctl start odoo17
            echo "=== Deploy Selesai ==="